# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerDeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('charity_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'charity')),
                ('charity_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'delivery')),
                ('delivery_option', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'order')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'role')),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sock',
            fields=[
                ('sock_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'sock')),
                ('sock_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='phone',
        ),
        migrations.AddField(
            model_name='buyer',
            name='areacode',
            field=models.IntegerField(default=555, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='exchange',
            field=models.IntegerField(default=555, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='extension',
            field=models.IntegerField(default=5555, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=b'buyer'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Buyer'),
        ),
        migrations.AddField(
            model_name='order',
            name='charity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Charity'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='sock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Sock'),
        ),
        migrations.AddField(
            model_name='buyerrole',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Buyer'),
        ),
        migrations.AddField(
            model_name='buyerrole',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Role'),
        ),
        migrations.AddField(
            model_name='buyerdeliveryinfo',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Buyer'),
        ),
    ]
