# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20170324_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='charity_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'charity'),
        ),
    ]
