# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20170324_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTest',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'order')),
                ('sock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Sock')),
            ],
        ),
    ]
