# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 19:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_ordertest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprehensive',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'Order')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. 10 digits allowed.", regex=b'^\\+?1?\\d{10,10}$')])),
                ('sock_id', models.IntegerField(choices=[(1, b'ESU Colors - Medium - Men (6-8) Donation $20'), (2, b'ESU Colors - Large - Men (9-13) Donation $20'), (3, b'Neon Colors - Medium - Men (6-8) Donation $20'), (4, b'Neon Colors - Large - Men (9-13) Donation $20'), (5, b'ESU Colors - Medium - Women (6-9) Donation $20'), (6, b'ESU Colors - Large - Women (10-13) Donation $20'), (7, b'Neon Colors - Medium - Women (6-9) Donation $20'), (8, b'Neon Colors - Large - Women (10-13) Donation $20')], default=0, verbose_name=b'Sock Choice')),
                ('charity_id', models.IntegerField(choices=[(1, b'Student'), (2, b'Community Member'), (3, b'Staff'), (4, b'Faculty'), (5, b'Administrator'), (6, b'Alumni')], default=0, verbose_name=b'Chairty')),
                ('role_id', models.IntegerField(choices=[(1, b'Street2Feet'), (2, b'The Good Project')], default=0, verbose_name=b'Role')),
                ('delivery_id', models.IntegerField(choices=[(1, b'I want to pick up my Socks. Socks are available for Pickup from the C.R.E.A.T.E. Lab (Stroud Hall, Room 107) Tuesdays & Wednesdays 1-4pm'), (2, b'I want my socks delivered. Delivery available on campus only. Delivery day is any Tuesday between 1-4pm')], default=0, verbose_name=b'Delivery Option')),
                ('building_name', models.CharField(blank=True, max_length=30, null=True)),
                ('room_number', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordertest',
            name='sock_id',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='areacode',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='extension',
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. 10 digits allowed.", regex=b'^\\+?1?\\d{10,10}$')]),
        ),
        migrations.AlterField(
            model_name='buyerdeliveryinfo',
            name='buyer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buyerrole',
            name='buyer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyerrole',
            name='role_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='charity_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='sock_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OrderTest',
        ),
    ]
