# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20170423_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdeliveryinfo',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Buyer'),
        ),
        migrations.AlterField(
            model_name='buyerrole',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Buyer'),
        ),
        migrations.AlterField(
            model_name='buyerrole',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Role'),
        ),
        migrations.AlterField(
            model_name='comprehensive',
            name='charity_id',
            field=models.IntegerField(choices=[(1, b'Street2Feet'), (2, b'The Good Project')], default=0, verbose_name=b'Charity'),
        ),
        migrations.AlterField(
            model_name='comprehensive',
            name='role_id',
            field=models.IntegerField(choices=[(1, b'Student'), (2, b'Community Member'), (3, b'Staff'), (4, b'Faculty'), (5, b'Administrator'), (6, b'Alumni')], default=0, verbose_name=b'Role'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Buyer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='charity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Charity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Sock'),
        ),
    ]
