# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20170427_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprehensive',
            name='charity_id',
            field=models.IntegerField(choices=[(1L, 'Street2Feet'), (2L, 'The Good Project'), (10L, 'Good Will Hunting'), (13L, 'Bon Jovi'), (18L, 'Moose'), (19L, 'beef'), (20L, 'red'), (21L, 'blue'), (22L, 'green')], default=0, verbose_name=b'Charity'),
        ),
    ]
